title: Live Web
description: Course website for Live Web at Interactive Media Arts, NYU Tisch
theme: just-the-docs

url: https://aidannelson.github.io/ima-live-web-fall-2024/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
